### ISSUE TITLE
DAS WG TPAC F2F agenda proposals

### ISSUE THREAD

**Issue by anssiko** [w3c/devicesensors-wg#22]
The [Devices and Sensors WG](https://www.w3.org/das/) (DAS WG) will meet at [TPAC 2018](https://www.w3.org/2018/10/TPAC/) on [Mon 22 Oct and Tue 23 Oct](https://www.w3.org/2018/10/TPAC/schedule.html). See the [DAS WG roadmap](https://www.w3.org/das/roadmap) for all the specs being worked on in the group.

This issue is to solicit early input on topics the group participants would like to discuss at F2F (see [F2F agenda](https://www.w3.org/wiki/DAS/Meetings/October_2018_F2F#Agenda)). To date, the chairs have received requests for the following topics:

* [Geolocation Sensor](https://w3c.github.io/geolocation-sensor/) - @tomayac to lead, Mon 14:00-15:30, revisit on Tue as needed
* [Generic Sensor Level 2](https://github.com/w3c/sensors/projects/5) - @reillyeon prefers Tue
  * Exposing sensors in service workers
  * Sensor discovery - @larsgk?
* WebDriver Extension API for Generic Sensor ([PR](https://github.com/w3c/sensors/pull/369)) - @reillyeon prefers Tue
* Discuss applicable findings from the [W3C Workshop on Permissions and User Consent](https://www.w3.org/Privacy/permissions-ws-2018/) - @ThomasTheDane to report out, @reillyeon prefers Tue
* [DeviceOrientation Event](https://w3c.github.io/deviceorientation/)
* [Battery Status API](https://w3c.github.io/battery/) - @anssiko to lead
* [Wake Lock API](https://w3c.github.io/wake-lock/)

Possible future work, not in scope of the DAS WG currently:

* [Serial API](https://wicg.github.io/serial/) ([migration to WICG expected](https://discourse.wicg.io/t/serial-api-moving-from-web-of-sensors-cg-to-web-incubator-cg/2940))
* [WebUSB API](https://wicg.github.io/webusb/)
* [Shape Detection API](https://wicg.github.io/shape-detection-api/)
* [Web NFC API](https://w3c.github.io/web-nfc/) - @kenchris wants to avoid overlap with TAG

**Comment by kenchris** [comment]
Are we doing something to invite other interested browser vendors, like Microsoft who has sensors under consideration now. If so, we could do some introductory presentations, touching on security etc.

Especially with regard to Web Bluetooth etc there is some common misunderstandings

**Comment by anssiko** [comment]
@kenchris, that's a good idea. Feel free to reach out to people, and let us know if there's preference on the day/time for such a session.

The discussion on the applicable findings from the upcoming W3C Workshop on Permissions and User Consent (participated by all major browser vendors) could be a good follow up session for interested browser vendors. In that session I'd expect us to disseminate concrete feedback from that workshop, and see how to reflect that into specs being worked on in this group.

**Comment by kenchris** [comment]
@patrickkettner might be interested, or know who is interested from MS side

**Comment by anssiko** [comment]
PTAL @reillyeon and @xfq.

**Comment by anssiko** [comment]
We might want to revisit the Sensor Discovery for Generic Sensor API topic at F2F. @larsgk has done investigation and might be able to share his findings at F2F, see https://github.com/w3c/sensors/issues/7

**Comment by reillyeon** [comment]
I am unfortunately not going to be able to make it to Monday's F2F. The topics I am most interested in discussing are,

- Generic Sensor Level 2
- Findings from the Permissions workshop
- The WebDriver Extension API for Generic Sensor

Is there any interest from participants in discussing the [Battery Status API](https://w3c.github.io/battery/) or [Wake Lock API](https://w3c.github.io/wake-lock/)?

Taking off my chair hat for a moment, I am interested in discussing the future path for the [Serial API](https://wicg.github.io/serial/) to move into the DAS WG after incubation as I would like to explore a similar path for the [WebUSB API](https://wicg.github.io/webusb/). Another API that could move from incubation to this WG is the [Shape Detection API](https://wicg.github.io/shape-detection-api/).

**Comment by ThomasTheDane** [comment]
I can give a report out from the W3C Permissions workshop happening in San Diego September 26 and 27. 
I'm attending both Monday and Tuesday

**Comment by anssiko** [comment]
>@ThomasTheDane: I can give a report out from the W3C Permissions workshop happening in San Diego September 26 and 27.
I'm attending both Monday and Tuesday

Thanks! Happy to have you report out the workshop findings. I'd tentatively schedule this for Tuesday since @reillyeon indicated interest to attend and is unavailable on Monday.

>@reillyeon: Taking off my chair hat for a moment, I am interested in discussing the future path for the Serial API to move into the DAS WG after incubation as I would like to explore a similar path for the WebUSB API. Another API that could move from incubation to this WG is the Shape Detection API.

Noted as "possible future work". We can discuss these time allowing, giving priority to specs in the WG charter.

>@reillyeon: Is there any interest from participants in discussing the Battery Status API [...]

I think it might be useful to look at the long-standing PR to allow use in same-origin children, add Feature Policy integration: https://github.com/w3c/battery/pull/13

Also couple of v2 issues to review: https://github.com/w3c/battery/issues

> [...]  or Wake Lock API?

I've asked whether there's any feedback from the ongoing implementation work. Additionally, there's one fairly recent issue raised by @mounirlamouri re GC behavior that might be worth discussing: https://github.com/w3c/wake-lock/issues/128

@mounirlamouri, you plan to attend the Media and Entertainment IG on TPAC Mon/Tue, but can you pop in at our meeting briefly on Mon or Tue to cover Wake Lock API and Battery Status API issues you've contributed to?

**Comment by kenchris** [comment]
I would like to talk about WebNFC and future steps

**Comment by anssiko** [comment]
Thanks @kenchris! Noted the Web NFC API, to be discussed time permitting. I assumed you are interested in leading this discussion.

**Comment by kenchris** [comment]
Sure

**Comment by tomayac** [comment]
(@anssiko For planning, I arrive on Monday 10:05 at LYS, so realistically will be at the venue only by 12:00. Hope this works agenda-wise?!)

**Comment by anssiko** [comment]
The first version of the F2F agenda has been published:

https://www.w3.org/wiki/DAS/Meetings/October_2018_F2F#Agenda

This issue is used to solicit input on further comments, suggestions.

**Comment by mounirlamouri** [comment]
Sorry for missing your message @anssiko. I would be happy to join you all to discuss the GC issue.

**Comment by tomayac** [comment]
@anssiko @mounirlamouri Sorry for the super late notice, but is there any chance we could shift the Wake Lock slot from 11AM to the 3:30PM Geo Sensor placeholder slot? (My constraint is that I can't be in Lyon before about noon-ish, apologies.)

Wake Lock will be essential for several Geo Sensor use cases like geofencing and geotracking, but I would also like to discuss a  specific idea that came up in context: https://github.com/w3c/wake-lock/issues/130. 

If it's not possible to change the schedule (absolutely fair if it isn't), I would like to ask @anssiko if it is possible to call in to the 11AM slot, I might be able to do that while transferring from the airport to the venue.

**Comment by anssiko** [comment]
@tomayac, we can discuss Wake Lock interactions with the Geolocation Sensor in the 3.30pm slot and GC and other generic topics in the 11am slot. I updated https://www.w3.org/wiki/DAS/Meetings/October_2018_F2F#Monday accordingly.

**Comment by tomayac** [comment]
Thank you very much, and sorry for flagging this so late again.

**Comment by anssiko** [comment]
Closing this TPAC 2018 agenda issue.

The draft agenda for the upcoming TPAC 2019 meeting is being worked on at https://github.com/w3c/devicesensors-wg/issues/24
