### ISSUE TITLE
Devices and Sensors WG - TPAC 2021 agenda

### ISSUE THREAD

**Issue by reillyeon** [w3c/devicesensors-wg#47]
This issue is to work out an agenda for the [Devices and Sensors WG](https://w3.org/das) meeting at [TPAC 2021](https://www.w3.org/2021/10/TPAC/), a virtual event that will be held from the 18th to the 29th of October 2021. The week from the 25th to the 29th will be dedicated to Joint and Group meetings.

# Registration

TPAC registration will open on 20 September 2021, register via https://www.w3.org/2021/10/TPAC/

# Logistics

CONFIRMED dates and times, 1-2 hours a day, subject to the agenda:

* ⏰ 27 Oct 2021, 5:00-7:00 UTC (see [your local time](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20211027T05)) - [🗓️ Calendar](https://www.w3.org/events/meetings/c1d1adc0-7093-4dac-97a2-a37c4526fb08)
* ⏰ 28 Oct 2021, 5:00-7:00 UTC (see [your local time](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20211028T05)) - [🗓️ Calendar](https://www.w3.org/events/meetings/c8a10439-616e-4784-b41a-0440acf4bccb)
* ⏰ 29 Oct 2021, 5:00-7:00 UTC (see [your local time](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20211029T05)) - [🗓️ Calendar](https://www.w3.org/events/meetings/1577c6af-a098-48bc-89d4-2618ddde3ebc)
- 📞 For Zoom details, see the meeting Calendar
- ✍️ [IRC](https://irc.w3.org/?channels=#dap) or irc://irc.w3.org:6667/#dap

# 27 Oct 2021, 5:00-7:00 UTC

## 📘 Charter update

- Charter 2021, new tentative deliverables and expectations @plehegar 

## 🆕 New work / new features

- Contact Picker API https://wicg.github.io/contact-api/spec/ @rayankans?
  - Path to FPWD, joint publication with WebApps WG @marcoscaceres @anssiko

- Compute Pressure API 
  - Origin Trial learnings @pwnall?
  - New backends arch review, new requirements? @kenchris @arskama

- Screen Wake Lock API https://w3c.github.io/screen-wake-lock/ @rakuco
  - Screen brightness mode https://github.com/w3c/screen-wake-lock/issues/129#issuecomment-817151517 @willmorgan 

- Idle Detection API https://wicg.github.io/idle-detection/
  - New user presence signal(s), alternative backends @anssiko @rakuco 
  - Origin Trial learnings @reillyeon

# 28 Oct 2021, 5:00-7:00 UTC

## 🔋 Other device capabilities

- Device Posture API https://w3c.github.io/device-posture/ (⏰ 5:00 UTC for @darktears)
  - Revised posture types: "continuous", "folded", "folded-over" @diekus @kenchris
  - TAG review status https://github.com/w3ctag/design-reviews/issues/575 @darktears
  - Semantic postures https://github.com/w3c/device-posture/issues/94 @diekus

- Screen Wake Lock API https://www.w3.org/TR/screen-wake-lock/
  - Path to CR, wide review https://github.com/w3c/screen-wake-lock/issues/270 @anssiko
  - Interaction with Page Life Cycle https://github.com/w3c/screen-wake-lock/issues/139 @jyasskin?

- Battery Status API
  - Private browsing mode special casing https://github.com/w3c/battery/issues/29 @samuelweiler
  - [merged] Make privacy mitigations normative https://github.com/w3c/battery/issues/27 @samuelweiler
  - Deprecation of non-SecureContext access to the getBattery() https://github.com/w3c/battery/issues/15 @rakuco @anssiko
  - Various editorial modernization updates (thanks @rakuco!)

- Network Information API
  - API rebooted to cater for new use cases https://lists.w3.org/Archives/Public/public-device-apis/2021Aug/0003.html @tomayac
  - Introduce and discuss the new proposed API https://raw.githack.com/tomayac/netinfo/relaunch/index.html (cf. the old API https://wicg.github.io/netinfo/) @tomayac

- Geolocation API
  - Path to CR->REC https://github.com/w3c/geolocation-api/issues/93 @anssiko
  - Explicitly limit permission lifetimes https://github.com/w3c/geolocation-api/issues/69 @pes10k @marcoscaceres 

- HTML Media Capture
  - Development transferred to WHATWG https://www.w3.org/2021/06/WHATWG-W3C-MOU_2021_update.html @anssiko

# 29 Oct 2021, 5:00-7:00 UTC

## 🔒 Privacy, security, and architecture

- "AB/TAG experiment" recommendations update @xfq @anssiko @reillyeon 
  - Specs in scope re-published as WDs, note the WG is pursuing modern security and privacy reviews
  - Discuss prerequisites for the reviews
- Privacy cross-group brainstorming @samuelweiler @npdoty @pes10k? @jonathankingston? 
  - PING - discuss privacy horizontal review expectations, see [how to get horizontal review](https://www.w3.org/Guide/documentreview/#how_to_get_horizontal_review)
  - Privacy CG - discuss [Privacy CG proposals](https://privacycg.github.io/charter.html#proposals), new proposals beneficial for this WG
  - Research - the user perspective of access to mobile sensors across platforms @maryammjd
- TAG collaboration @kenchris?
  - TAG review status check, any specific issues to seek advice on from the TAG?

## 📡 Sensors

- Sensors and permission bundles, low-level vs. high-level permissions https://github.com/w3c/permissions/issues/191 @tomayac
- Support non-"fully active" documents https://github.com/w3c/sensors/issues/415
- [merged] Concrete sensors and default allowlist https://github.com/w3c/accelerometer/pull/61 @anssiko
- Ambient Light Sensor, consider making granularity of the data normative https://github.com/w3c/ambient-light/issues/63 @jonathanKingston?
- Ambient Light Sensor, revisit developer feedback https://github.com/w3c/ambient-light/issues/64
- Magnetometer, discuss any spec blockers for shipping

# Minutes

- https://www.w3.org/2021/10/27-dap-minutes.html
- https://www.w3.org/2021/10/28-dap-minutes.html
- https://www.w3.org/2021/10/29-dap-minutes.html
- https://www.w3.org/2021/11/17-dap-minutes.html (Brightness mode follow-up meeting)

# Participants

All Devices and Sensors WG participants and invited guests.

**Comment by tomayac** [comment]
> - Network Information API
> 
> Introduce and discuss the new proposed API https://ghcdn.rawgit.org/tomayac/netinfo/relaunch/index.html

This service has somehow gone stale and has a certificate issue. The new URL is https://raw.githack.com/tomayac/netinfo/relaunch/index.html. Please change in the original comment (and feel free to delete this comment after doing so).

**Comment by anssiko** [comment]
Update: fixed the URL to the new proposed Network Information API in the agenda: https://raw.githack.com/tomayac/netinfo/relaunch/index.html

@tomayac, thanks for reporting!

**Comment by marcoscaceres** [comment]
Agenda looks great! 😍 Looking forward to meeting.

**Comment by anssiko** [comment]
Thanks everyone for your responses to the [scheduling poll](https://doodle.com/poll/psykbngp3z3m4xwu).

We've now confirmed the DAS WG TPAC meeting dates and times as follows taking into account your preferences:

* ⏰ 27 Oct 2021, 5:00 UTC (see [your local time](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20211027T05))
* ⏰ 28 Oct 2021, 5:00 UTC (see [your local time](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20211028T05))
* ⏰ 29 Oct 2021, 5:00 UTC (see [your local time](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20211029T05))

We'll meet 1-2 hours each day, subject to the agenda and participants' availability.

All DAS WG participants and invited guests will receive meeting invitations with logistics.

**Comment by kenchris** [comment]
Hi @anssiko I am doing a Fugu panel with Thomas Nattestad and Christian Liebel the 27 as 9am CET, so I will probably only join from 7-8am then. Can we please schedule around that, so that the parts that I will need to participate doesn't happen the 27th from 8-9am CET? :)

**Comment by darktears** [comment]
The meeting is going to be 1AM my time so if the device posture section could be scheduled first thing in one of the days, I would appreciate it very much.

**Comment by anssiko** [comment]
@darktears I'm sympathetic to that request and we'll do our best to accommodate that.

**Comment by reillyeon** [comment]
Thank you everyone for attending our TPAC 2021 meetings.
