### ISSUE TITLE
Add Compute Pressure and Contact Picker API to Repository Manager

### ISSUE THREAD

**Issue by anssiko** [w3c/devicesensors-wg#64]
The following error appears for PRs submitted by WG participants:

>The repository manager doesn't know the following repository: w3c/compute-pressure

Example: https://github.com/w3c/compute-pressure/pull/171 and https://labs.w3.org/repo-manager/pr/id/w3c/compute-pressure/171

My expectation is the same error would appear for PRs for the w3c/contact-picker repo too, so that should also be added to the repo manager and configured as a joint deliverable between the DAS WG and WebApps WG to allow participants from both the WGs submit PRs.

**Comment by anssiko** [comment]
@himorin @vivienlacourba another what I suspect is a related error in https://labs.w3.org/repo-manager/pr/id/w3c/compute-pressure/172:

>PR not found: w3c/compute-pressure/pulls/172

To reproduce, go to https://labs.w3.org/repo-manager/pr/id/w3c/compute-pressure/172 and click "Revalidate" or "Mark as non-substantive".

**Comment by vivienlacourba** [comment]
> @himorin @vivienlacourba another what I suspect is a related error in https://labs.w3.org/repo-manager/pr/id/w3c/compute-pressure/172:
> 
> > PR not found: w3c/compute-pressure/pulls/172
> 
> To reproduce, go to https://labs.w3.org/repo-manager/pr/id/w3c/compute-pressure/172 and click "Revalidate" or "Mark as non-substantive".

This was fixed with @deniak's help.

**Comment by anssiko** [comment]
Thanks @himorin @vivienlacourba @deniak for your support and swift fix to this issue!
